import { loadData } from "@/lib/data";
import { DataFreshness, LimitationCallout, SectionHeader } from "@/components/ui";
import { MultiColorBarChart, SimpleBarChart } from "@/components/DashboardCharts";
import { formatPercent } from "@/lib/format";

interface QualityData { cutoff: string; distribution: Array<{ status: string; events: number; behavioral_use: boolean }>; coverage: { main: number; strict: number; warning_share_of_usable: number; quarantine_share: number }; quality_backlog: { accounts: number; label: string }; anomalies: Array<Record<string, string | number>>; subscription_overlap: { episodes: number; overlapping_episode_ratio: number; subscriptions_with_warning: number }; reconciliation: { unexplained_difference: number }; privacy: { pii_exposed: number; future_leakage: number }; tooltips: string[]; limitations: string[] }

export default async function QualityPage() {
  const quality = await loadData<QualityData>("quality.json");
  const coverage = [{ population: "MAIN", coverage: quality.coverage.main * 100 }, { population: "STRICT", coverage: quality.coverage.strict * 100 }];
  return <div><SectionHeader eyebrow="Data & quality" title="Quality is controlled, not hidden." description="Every event is gated before behavioral use. Warning-bearing evidence stays visible, while quarantined events are reserved for data-quality review only." /><DataFreshness cutoff={quality.cutoff} /><div className="mt-7 grid gap-5 xl:grid-cols-2"><MultiColorBarChart data={quality.distribution.map(({ status, events }) => ({ status, events }))} category="status" value="events" title="Event quality distribution" subtitle="Events processed before and after quality gates · cutoff Dec 31, 2024" summary="13,927 events are usable in MAIN; 21,659 quarantined events are excluded from behavioral evidence." /><SimpleBarChart data={coverage} category="population" value="coverage" title="MAIN versus STRICT coverage" subtitle="Percent of 35,586 processed events" summary={`MAIN covers ${formatPercent(quality.coverage.main)} and STRICT covers ${formatPercent(quality.coverage.strict)}.`} /></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Data quality backlog", value: quality.quality_backlog.accounts, note: "Separate from behavioral queues" }, { label: "Subscription episodes", value: quality.subscription_overlap.episodes, note: "Overlap remains a source warning" }, { label: "Unexplained difference", value: quality.reconciliation.unexplained_difference, note: "Reconciliation gate" }, { label: "PII / leakage", value: quality.privacy.pii_exposed + quality.privacy.future_leakage, note: "Both controls equal zero" }].map((item) => <article className="panel p-5" key={item.label}><p className="data-label">{item.label}</p><p className="mt-2 font-mono text-3xl font-semibold">{item.value}</p><p className="mt-2 text-sm text-muted">{item.note}</p></article>)}</div><div className="mt-6"><LimitationCallout title="Data quality backlog">{quality.quality_backlog.label}</LimitationCallout></div><section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="panel p-5"><h3 className="font-semibold">How to read quality states</h3><ul className="mt-4 space-y-3">{quality.tooltips.map((tip) => <li className="rounded-lg bg-slate-50 p-3 text-sm leading-6 text-slate-700" key={tip}>{tip}</li>)}</ul></article><article className="panel p-5"><h3 className="font-semibold">Primary limitations</h3><ul className="mt-4 list-disc space-y-3 pl-5 text-sm leading-6 text-slate-700">{quality.limitations.map((limitation) => <li key={limitation}>{limitation}</li>)}</ul></article></section></div>;
}
