"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Clock3 } from "lucide-react";
interface DemoStep { step: number; title: string; route: string; sentence: string; metric: string; insight: string; limitation: string }
const routeLabels: Record<string, string> = { "/": "visão geral", "/quality": "qualidade dos dados", "/journeys": "jornadas", "/graph": "grafo", "/watchlist": "fila de revisão", "/experiments": "experimentos", "/governance": "governança" };
export function GuidedDemo({ steps, duration }: { steps: DemoStep[]; duration: string }) {
  const [index, setIndex] = useState(0); const current = steps[index];
  return <section className="panel overflow-hidden"><div className="border-b border-line bg-ink p-6 text-white md:p-8"><div className="flex items-center gap-2 text-sm text-slate-300"><Clock3 size={16} aria-hidden />Narrativa de {duration} minutos</div><p className="mt-5 text-xs font-bold uppercase tracking-[0.2em] text-slate-300">Etapa {current.step} de {steps.length}</p><h3 className="mt-2 text-3xl font-semibold">{current.title}</h3><p className="mt-3 max-w-2xl text-slate-300">{current.sentence}</p></div><div className="grid gap-6 p-6 md:grid-cols-3 md:p-8"><div><p className="data-label">Rota visual</p><Link href={current.route} className="mt-2 inline-flex text-lg font-semibold text-blue hover:underline">Abrir {routeLabels[current.route]} <ArrowRight className="ml-2" size={18} /></Link></div><div><p className="data-label">Métrica</p><p className="mt-2 font-mono text-xl font-semibold">{current.metric}</p></div><div><p className="data-label">Insight</p><p className="mt-2 text-sm leading-6">{current.insight}</p></div><div className="md:col-span-3 rounded-xl border border-gold/40 bg-amber-50 p-4"><p className="data-label">Limitação</p><p className="mt-1 text-sm text-slate-700">{current.limitation}</p></div></div><div className="flex items-center justify-between border-t border-line p-5"><button className="button-secondary" disabled={index === 0} onClick={() => setIndex((value) => Math.max(0, value - 1))}><ArrowLeft className="mr-2" size={16} />Anterior</button><div className="flex gap-1" aria-label="Progresso da demonstração">{steps.map((step, stepIndex) => <span key={step.step} className={`h-2 w-6 rounded-full ${stepIndex === index ? "bg-blue" : "bg-slate-200"}`} />)}</div><button className="button-primary" disabled={index === steps.length - 1} onClick={() => setIndex((value) => Math.min(steps.length - 1, value + 1))}>Próxima<ArrowRight className="ml-2" size={16} /></button></div></section>;
}
