"use client";

import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Search, X } from "lucide-react";
import type { WatchlistItem } from "@/lib/types";
import { EvidenceBadge, ExplainThis, LimitationCallout, ProvenancePanel, StatusBadge } from "@/components/ui";
import { humanize } from "@/lib/format";

const PAGE_SIZE = 10;

export function WatchlistDetailDrawer({ item, close }: { item: WatchlistItem; close: () => void }) {
  return <div className="fixed inset-0 z-50 flex justify-end" role="dialog" aria-modal="true" aria-labelledby="watchlist-drawer-title"><button className="absolute inset-0 bg-ink/50" onClick={close} aria-label="Close watchlist detail" /><aside className="relative h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">{item.rule.id} · {humanize(item.queue)}</p><h2 id="watchlist-drawer-title" className="mt-2 font-mono text-xl font-semibold">{item.account_key}</h2></div><button onClick={close} className="rounded-lg border border-line p-2" aria-label="Close detail"><X size={18} /></button></div><div className="mt-5 flex flex-wrap gap-2"><StatusBadge value={item.priority} /><EvidenceBadge value={item.evidence_strength} /><StatusBadge value={item.data_confidence} /></div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><div><dt className="data-label">Rule triggered</dt><dd className="mt-1 text-sm font-semibold">{humanize(item.rule.name)}</dd></div><div><dt className="data-label">Human owner</dt><dd className="mt-1 text-sm">{item.human_owner}</dd></div><div><dt className="data-label">Quality profile</dt><dd className="mt-1 text-sm">{item.data_confidence} · {(item.quality_coverage * 100).toFixed(1)}% coverage</dd></div><div><dt className="data-label">Limitation count</dt><dd className="mt-1 font-mono text-lg">{item.limitation_count}</dd></div></dl><div className="mt-6 space-y-3"><p className="rounded-xl bg-olive/10 p-3 text-sm font-semibold text-olive">Requires human review: Yes</p><p className="rounded-xl bg-orange/10 p-3 text-sm font-semibold text-orange">Automatic intervention: Not allowed</p></div><div className="mt-6"><ExplainThis data={item.explanation} /></div>{item.explanation.provenance && <div className="mt-5"><ProvenancePanel value={item.explanation.provenance} /></div>}<LimitationCallout title="Allowed use"><span>{item.authorized_investigation}</span></LimitationCallout></aside></div>;
}

export function WatchlistTable({ items }: { items: WatchlistItem[] }) {
  const [query, setQuery] = useState("");
  const [queue, setQueue] = useState("ALL");
  const [category, setCategory] = useState("BEHAVIORAL_INVESTIGATION");
  const [page, setPage] = useState(0);
  const [selected, setSelected] = useState<WatchlistItem | null>(null);
  const queues = Array.from(new Set(items.map((item) => item.queue))).sort();
  const filtered = useMemo(() => items.filter((item) => item.category === category && (queue === "ALL" || item.queue === queue) && item.account_key.toLowerCase().includes(query.toLowerCase())).sort((a, b) => a.priority.localeCompare(b.priority) || a.account_key.localeCompare(b.account_key)), [items, query, queue, category]);
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const visible = filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);
  const setFilter = (callback: () => void) => { callback(); setPage(0); };
  return <section className="space-y-4">
    <div className="panel flex flex-wrap gap-3 p-4">
      <div className="inline-flex rounded-lg border border-line p-1" aria-label="Watchlist category"><button className={`rounded-md px-3 py-2 text-sm font-semibold ${category === "BEHAVIORAL_INVESTIGATION" ? "bg-ink text-white" : "text-muted"}`} onClick={() => setFilter(() => setCategory("BEHAVIORAL_INVESTIGATION"))}>Behavioral watchlist</button><button className={`rounded-md px-3 py-2 text-sm font-semibold ${category === "DATA_QUALITY_BACKLOG" ? "bg-ink text-white" : "text-muted"}`} onClick={() => setFilter(() => setCategory("DATA_QUALITY_BACKLOG"))}>Data quality review</button></div>
      <label className="relative min-w-64 flex-1"><span className="sr-only">Search anonymous account key</span><Search className="absolute left-3 top-3 text-muted" size={16} aria-hidden /><input className="input-control w-full pl-9" value={query} onChange={(event) => setFilter(() => setQuery(event.target.value))} placeholder="Search account_key" /></label>
      <label><span className="sr-only">Filter by queue</span><select className="input-control" value={queue} onChange={(event) => setFilter(() => setQueue(event.target.value))}><option value="ALL">All queues</option>{queues.map((value) => <option key={value}>{value}</option>)}</select></label>
    </div>
    <div className="panel overflow-hidden">
      {visible.length === 0 ? <div className="p-8 text-center"><p className="font-semibold">No review item matches these filters.</p><button className="button-secondary mt-4" onClick={() => { setQuery(""); setQueue("ALL"); setPage(0); }}>Reset filters</button></div> : <><div className="hidden overflow-x-auto md:block"><table className="w-full border-collapse text-left text-sm"><caption className="sr-only">Bounded anonymous watchlist demo items</caption><thead className="bg-slate-50 text-xs uppercase tracking-wide text-muted"><tr>{["Account key", "Queue", "Priority", "Evidence", "Urgency", "Materiality", "Confidence", "MRR band", "Review"].map((label) => <th className="px-4 py-3" key={label} scope="col">{label}</th>)}</tr></thead><tbody>{visible.map((item) => <tr className="border-t border-line hover:bg-slate-50" key={item.watchlist_item_key}><td className="px-4 py-3 font-mono text-xs">{item.account_key}</td><td className="px-4 py-3">{humanize(item.queue)}</td><td className="px-4 py-3"><StatusBadge value={item.priority} /></td><td className="px-4 py-3">{humanize(item.evidence_strength)}</td><td className="px-4 py-3">{humanize(item.temporal_urgency)}</td><td className="px-4 py-3">{humanize(item.materiality)}</td><td className="px-4 py-3">{humanize(item.data_confidence)}</td><td className="px-4 py-3">{humanize(item.associated_mrr_band)}</td><td className="px-4 py-3"><button className="font-semibold text-blue underline-offset-4 hover:underline" onClick={() => setSelected(item)}>View evidence</button></td></tr>)}</tbody></table></div><div className="space-y-3 p-4 md:hidden">{visible.map((item) => <article className="rounded-xl border border-line p-4" key={item.watchlist_item_key}><div className="flex items-start justify-between gap-2"><p className="font-mono text-xs">{item.account_key}</p><StatusBadge value={item.priority} /></div><p className="mt-3 text-sm font-semibold">{humanize(item.queue)}</p><p className="mt-1 text-xs text-muted">{humanize(item.evidence_strength)} evidence · {humanize(item.data_confidence)} confidence</p><button className="button-secondary mt-4 w-full" onClick={() => setSelected(item)}>View evidence</button></article>)}</div></>}
      <div className="flex items-center justify-between border-t border-line px-4 py-3 text-sm"><span>{filtered.length} bounded demo items</span><div className="flex items-center gap-2"><button className="rounded border border-line p-2 disabled:opacity-30" disabled={page === 0} onClick={() => setPage((value) => Math.max(0, value - 1))} aria-label="Previous page"><ChevronLeft size={16} /></button><span className="font-mono text-xs">{page + 1} / {pages}</span><button className="rounded border border-line p-2 disabled:opacity-30" disabled={page + 1 >= pages} onClick={() => setPage((value) => Math.min(pages - 1, value + 1))} aria-label="Next page"><ChevronRight size={16} /></button></div></div>
    </div>
    {selected && <WatchlistDetailDrawer item={selected} close={() => setSelected(null)} />}
  </section>;
}
