import { loadData } from "@/lib/data";
import { DataFreshness, LimitationCallout, SectionHeader } from "@/components/ui";

interface Metadata { data_cutoff: string; dashboard_version: string; source_commit: string; pipeline_phases: number[]; artifact_hashes: Record<string, string> }

export default async function MethodologyPage() {
  const metadata = await loadData<Metadata>("metadata.json");
  return <div><SectionHeader eyebrow="Metodologia" title="Uma camada local de demonstração rastreável." description="O painel não recalcula achados analíticos. Uma compilação determinística em Python valida hashes de origem e gera JSONs compactos e seguros para o navegador." /><DataFreshness cutoff={metadata.data_cutoff} /><section className="mt-7 grid gap-5 md:grid-cols-2"><article className="panel p-5"><h3 className="font-semibold">Contrato de compilação</h3><dl className="mt-4 space-y-3 text-sm"><div><dt className="data-label">Versão do painel</dt><dd className="mt-1 font-mono">{metadata.dashboard_version}</dd></div><div><dt className="data-label">Commit de origem</dt><dd className="mt-1 break-all font-mono">{metadata.source_commit}</dd></div><div><dt className="data-label">Fases do fluxo</dt><dd className="mt-1">{metadata.pipeline_phases.join(" → ")}</dd></div><div><dt className="data-label">Status de PII</dt><dd className="mt-1">Nenhuma PII exposta</dd></div><div><dt className="data-label">Status causal</dt><dd className="mt-1">Sem alegação causal</dd></div></dl></article><article className="panel p-5"><h3 className="font-semibold">Integridade das fontes</h3><p className="mt-2 text-sm text-muted">{Object.keys(metadata.artifact_hashes).length} artefatos das Fases 3–8 passam por controle SHA-256 antes de cada compilação dos dados.</p><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-blue">Ver hashes das fontes</summary><pre className="mt-3 max-h-80 overflow-auto rounded-xl bg-ink p-4 text-xs text-slate-100">{JSON.stringify(metadata.artifact_hashes, null, 2)}</pre></details></article></section><div className="mt-7"><LimitationCallout>Não há serviço de aplicação ao vivo, autenticação, mutação, contato com clientes, banco externo ou chamada a modelo externo. Artefatos locais ausentes ou inválidos bloqueiam somente a seção afetada com uma mensagem legível.</LimitationCallout></div></div>;
}
