import { loadData } from "@/lib/data";
import { DataFreshness, LimitationCallout, SectionHeader } from "@/components/ui";

interface Metadata { data_cutoff: string; dashboard_version: string; source_commit: string; pipeline_phases: number[]; artifact_hashes: Record<string, string>; limitations: string[]; pii_status: string; causal_status: string }

export default async function MethodologyPage() {
  const metadata = await loadData<Metadata>("metadata.json");
  return <div><SectionHeader eyebrow="Methodology" title="A traceable local demonstration layer." description="The dashboard does not recalculate analytical findings. A deterministic Python build validates source hashes and emits compact browser-safe JSON." /><DataFreshness cutoff={metadata.data_cutoff} /><section className="mt-7 grid gap-5 md:grid-cols-2"><article className="panel p-5"><h3 className="font-semibold">Build contract</h3><dl className="mt-4 space-y-3 text-sm"><div><dt className="data-label">Dashboard version</dt><dd className="mt-1 font-mono">{metadata.dashboard_version}</dd></div><div><dt className="data-label">Source commit</dt><dd className="mt-1 break-all font-mono">{metadata.source_commit}</dd></div><div><dt className="data-label">Pipeline phases</dt><dd className="mt-1">{metadata.pipeline_phases.join(" → ")}</dd></div><div><dt className="data-label">PII status</dt><dd className="mt-1">{metadata.pii_status}</dd></div><div><dt className="data-label">Causal status</dt><dd className="mt-1">{metadata.causal_status}</dd></div></dl></article><article className="panel p-5"><h3 className="font-semibold">Source integrity</h3><p className="mt-2 text-sm text-muted">{Object.keys(metadata.artifact_hashes).length} Phase 3–8 source artifacts are SHA-256 gated before each data build.</p><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-blue">View source hashes</summary><pre className="mt-3 max-h-80 overflow-auto rounded-xl bg-ink p-4 text-xs text-slate-100">{JSON.stringify(metadata.artifact_hashes, null, 2)}</pre></details></article></section><div className="mt-7"><LimitationCallout>No live backend, authentication, mutation, customer contact, external database, or external model call is included. Missing or invalid local artifacts block only the affected section with a readable error.</LimitationCallout></div></div>;
}
