import type { DataQualityReport, ModelReport, Opportunity } from "@/lib/types";

export const SAMPLE_OPPORTUNITIES: Opportunity[] = [
  {
    opportunityId: "DEV-FOCUS-01",
    salesAgent: "Darcel Schlecht",
    manager: "Melvin Marxen",
    regionalOffice: "Central",
    product: "GTX Pro",
    productRaw: "GTXPro",
    productSeries: "GTX",
    account: "Isdom",
    accountDetails: { sector: "technology", revenue: 851.4, employees: 1402 },
    dealStage: "Engaging",
    engageDate: "2017-11-22",
    ageDays: 39,
    estimatedValue: 5148,
    probability: 78,
    priorityScore: 87,
    qualificationScore: null,
    scoreBreakdown: {
      conversion: 78,
      actionability: 90,
      valuePotential: 93,
      weightedContribution: { conversion: 51, actionability: 18, value: 14 },
    },
    queue: "Foco agora",
    confidence: "high",
    reasons: ["Faixa de ciclo com melhor conversão histórica", "Valor acima da mediana do produto"],
    dataQualityFlags: ["Produto normalizado de GTXPro para GTX Pro"],
    nextAction: "Confirmar decisor e agendar próximo passo ainda hoje.",
    rankGlobal: 1,
    rankByAgent: 1,
  },
  {
    opportunityId: "DEV-ACCEL-02",
    salesAgent: "Moses Frase",
    manager: "Dustin Brinkmann",
    regionalOffice: "Central",
    product: "GTX Plus Basic",
    productRaw: "GTX Plus Basic",
    productSeries: "GTX",
    account: "Cancity",
    accountDetails: { sector: "retail", revenue: 632.1, employees: 1180 },
    dealStage: "Engaging",
    engageDate: "2017-10-19",
    ageDays: 73,
    estimatedValue: 1830,
    probability: 63,
    priorityScore: 72,
    qualificationScore: null,
    scoreBreakdown: {
      conversion: 63,
      actionability: 80,
      valuePotential: 73,
      weightedContribution: { conversion: 41, actionability: 16, value: 11 },
    },
    queue: "Acelerar",
    confidence: "high",
    reasons: ["Boa probabilidade de conversão", "Deal ainda dentro do ciclo saudável"],
    dataQualityFlags: [],
    nextAction: "Remover a principal objeção e formalizar data de decisão.",
    rankGlobal: 14,
    rankByAgent: 1,
  },
  {
    opportunityId: "DEV-NURTURE-03",
    salesAgent: "Anna Snelling",
    manager: "Dustin Brinkmann",
    regionalOffice: "Central",
    product: "MG Special",
    productRaw: "MG Special",
    productSeries: "MG",
    account: "Ron-tech",
    accountDetails: { sector: "medical", revenue: 223.8, employees: 534 },
    dealStage: "Engaging",
    engageDate: "2017-09-04",
    ageDays: 118,
    estimatedValue: 61,
    probability: 39,
    priorityScore: 44,
    qualificationScore: null,
    scoreBreakdown: {
      conversion: 39,
      actionability: 50,
      valuePotential: 47,
      weightedContribution: { conversion: 25, actionability: 10, value: 7 },
    },
    queue: "Nutrir",
    confidence: "medium",
    reasons: ["Sinal de conversão moderado", "Valor potencial baixo para ação imediata"],
    dataQualityFlags: [],
    nextAction: "Manter cadência leve e validar mudança de urgência.",
    rankGlobal: 512,
    rankByAgent: 12,
  },
  {
    opportunityId: "DEV-RESCUE-04",
    salesAgent: "Vicki Laflamme",
    manager: "Melvin Marxen",
    regionalOffice: "Central",
    product: "GTX Basic",
    productRaw: "GTX Basic",
    productSeries: "GTX",
    account: "J-Texon",
    accountDetails: { sector: "services", revenue: 404.7, employees: 902 },
    dealStage: "Engaging",
    engageDate: "2017-05-23",
    ageDays: 222,
    estimatedValue: 590,
    probability: 12,
    priorityScore: 19,
    qualificationScore: null,
    scoreBreakdown: {
      conversion: 12,
      actionability: 20,
      valuePotential: 47,
      weightedContribution: { conversion: 8, actionability: 4, value: 7 },
    },
    queue: "Resgatar ou desqualificar",
    confidence: "low",
    reasons: ["Tempo aberto muito acima do ciclo histórico", "Estimativa fora do suporte dos ciclos encerrados"],
    dataQualityFlags: ["outside_historical_cycle"],
    nextAction: "Fazer última tentativa com prazo e encerrar se não houver avanço.",
    rankGlobal: 1860,
    rankByAgent: 47,
  },
  {
    opportunityId: "DEV-QUALIFY-05",
    salesAgent: "Cecily Lampkin",
    manager: "Dustin Brinkmann",
    regionalOffice: "Central",
    product: "GTX Plus Pro",
    productRaw: "GTX Plus Pro",
    productSeries: "GTX",
    account: null,
    accountDetails: null,
    dealStage: "Prospecting",
    engageDate: null,
    ageDays: null,
    estimatedValue: 0,
    probability: null,
    priorityScore: null,
    qualificationScore: 58,
    scoreBreakdown: null,
    queue: "Qualificar",
    confidence: "low",
    reasons: ["Lead ainda sem histórico de engajamento", "Conta não informada"],
    dataQualityFlags: ["Conta ausente", "Sem data de engajamento"],
    nextAction: "Identificar conta, dor e potencial antes de comparar com deals ativos.",
    rankGlobal: null,
    rankByAgent: null,
  },
];

export const SAMPLE_MODEL_REPORT: ModelReport = {
  model: "scoring híbrido temporal",
  target: "probabilidade de Won nos próximos 60 dias",
  scoreWeights: { conversion: 65, actionability: 20, value: 15 },
  validation: "split temporal com agrupamento por oportunidade",
  note: "Amostra de desenvolvimento; execute a pipeline para ver as métricas reais.",
};

export const SAMPLE_DATA_QUALITY: DataQualityReport = {
  note: "Amostra de desenvolvimento",
  checks: ["Conta ausente", "Data de engajamento ausente", "Normalização de produto"],
};
