/*
  # Enable pgvector and create Knowledge Base tables — Subfase 3.6

  ## Summary
  Enables the pgvector extension and creates the three-table schema for the
  RAG (Retrieval-Augmented Generation) engine.

  Documents are uploaded and split into overlapping chunks. Each chunk
  receives an embedding vector generated by the gte-small model (384 dims)
  so that semantic similarity searches can be performed at query time.

  ## New Tables

  ### knowledge_documents
  - `id`         – UUID primary key
  - `title`      – human-readable document title
  - `source`     – optional source URL or file reference
  - `content`    – full raw text of the document
  - `chunk_count`– number of chunks generated from this document
  - `status`     – processing lifecycle (pending | processing | ready | error)
  - `created_at` – insertion timestamp
  - `updated_at` – last update timestamp

  ### knowledge_chunks
  - `id`           – UUID primary key
  - `document_id`  – FK → knowledge_documents (cascade delete)
  - `chunk_text`   – the actual text of this chunk
  - `chunk_index`  – ordering index within the document
  - `created_at`   – insertion timestamp

  ### knowledge_embeddings
  - `id`        – UUID primary key
  - `chunk_id`  – FK → knowledge_chunks (cascade delete)
  - `embedding` – VECTOR(384) produced by gte-small model
  - `created_at`– insertion timestamp

  ## Security
  - RLS enabled on all three tables
  - Authenticated users can read all knowledge tables
  - Only admins (via service role in edge functions) can insert/update/delete

  ## Notes
  1. VECTOR(384) matches the gte-small embedding dimension.
  2. An IVFFlat index is created on knowledge_embeddings for fast cosine
     similarity queries once the table has data.
  3. knowledge_documents.status tracks async processing pipeline state.
*/

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS knowledge_documents (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title       text NOT NULL,
  source      text NOT NULL DEFAULT '',
  content     text NOT NULL,
  chunk_count integer NOT NULL DEFAULT 0,
  status      text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'ready', 'error')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_knowledge_documents_status ON knowledge_documents(status);
CREATE INDEX IF NOT EXISTS idx_knowledge_documents_created ON knowledge_documents(created_at DESC);

ALTER TABLE knowledge_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read knowledge documents"
  ON knowledge_documents FOR SELECT
  TO authenticated
  USING (true);

CREATE TABLE IF NOT EXISTS knowledge_chunks (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
  chunk_text  text NOT NULL,
  chunk_index integer NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_document ON knowledge_chunks(document_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_index    ON knowledge_chunks(document_id, chunk_index);

ALTER TABLE knowledge_chunks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read knowledge chunks"
  ON knowledge_chunks FOR SELECT
  TO authenticated
  USING (true);

CREATE TABLE IF NOT EXISTS knowledge_embeddings (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  chunk_id   uuid NOT NULL REFERENCES knowledge_chunks(id) ON DELETE CASCADE,
  embedding  vector(384),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_knowledge_embeddings_chunk
  ON knowledge_embeddings(chunk_id);

ALTER TABLE knowledge_embeddings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read knowledge embeddings"
  ON knowledge_embeddings FOR SELECT
  TO authenticated
  USING (true);
