"""Build notebooks 05, 06, 07 for OptiFlow ML experiments."""
import json
import os

def build_notebook(cells, filename, kernel="optiflow"):
    nb = {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": kernel, "language": "python", "name": kernel},
            "language_info": {"name": "python", "version": "3.9.6"}
        },
        "cells": cells
    }
    with open(filename, 'w') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print(f"Created {filename} with {len(cells)} cells")

def md(text):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': [text]}

def code(text):
    return {'cell_type': 'code', 'metadata': {}, 'source': [text], 'execution_count': None, 'outputs': []}


# =====================================================
# NOTEBOOK 05: ML EXPERIMENTS
# =====================================================
def build_05():
    cells = []

    cells.append(md(
        "# 05 — Experimentos ML: Gradient Boosting + SHAP\n\n"
        "## Objetivo\n"
        "Validar sistematicamente quais variáveis influenciam a satisfação do cliente (CSAT) "
        "usando modelos de árvore (Gradient Boosting) e análise SHAP.\n\n"
        "Foco: **Canal e Assunto são acionáveis** — queremos entender como tempo e outras "
        "variáveis afetam CSAT dentro de cada combinação canal × assunto."
    ))

    cells.append(code(
        "import pandas as pd\n"
        "import numpy as np\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n"
        "from scipy import stats\n"
        "from scipy.stats import pearsonr\n"
        "from sklearn.model_selection import train_test_split, cross_val_score\n"
        "from sklearn.preprocessing import OrdinalEncoder\n"
        "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\n"
        "from sklearn.inspection import permutation_importance\n"
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n"
        "import os\n\n"
        "try:\n"
        "    from xgboost import XGBRegressor\n"
        "    USE_XGB = True\n"
        "    print('Usando XGBoost')\n"
        "except Exception:\n"
        "    from sklearn.ensemble import GradientBoostingRegressor\n"
        "    USE_XGB = False\n"
        "    print('XGBoost indisponivel, usando GradientBoostingRegressor')\n\n"
        "try:\n"
        "    import shap\n"
        "    USE_SHAP = True\n"
        "    print('SHAP disponivel')\n"
        "except Exception:\n"
        "    USE_SHAP = False\n"
        "    print('SHAP indisponivel')\n\n"
        "RANDOM_STATE = 42\n"
        "TEST_SIZE = 0.2\n\n"
        "csv_path = '../data/customer_support_tickets.csv'\n"
        "if not os.path.exists(csv_path):\n"
        "    csv_path = 'data/customer_support_tickets.csv'\n"
        "df_raw = pd.read_csv(csv_path)\n"
        "print(f'Dataset carregado: {len(df_raw)} tickets')\n\n"
        "df = df_raw[df_raw['Ticket Status'] == 'Closed'].copy()\n"
        "print(f'Tickets Closed: {len(df)}')\n\n"
        "df['First Response Time'] = pd.to_datetime(df['First Response Time'], errors='coerce')\n"
        "df['Time to Resolution'] = pd.to_datetime(df['Time to Resolution'], errors='coerce')\n"
        "df['duration_hours'] = (df['Time to Resolution'] - df['First Response Time']).dt.total_seconds().abs() / 3600\n"
        "df = df.dropna(subset=['Customer Satisfaction Rating', 'duration_hours'])\n"
        "print(f'Com CSAT + duracao: {len(df)}')\n"
        "print('Distribuicao CSAT:')\n"
        "print(df['Customer Satisfaction Rating'].value_counts().sort_index())\n"
        "print(f'Duracao (horas): media={df[\"duration_hours\"].mean():.1f}, mediana={df[\"duration_hours\"].median():.1f}')"
    ))

    cells.append(md("## Secao 1: Preparacao dos Dados"))

    cells.append(code(
        "df['age_bucket'] = pd.cut(df['Customer Age'], bins=[0, 25, 35, 45, 55, 100],\n"
        "                          labels=['18-25', '26-35', '36-45', '46-55', '56-70'])\n"
        "df['channel_subject'] = df['Ticket Channel'] + '_' + df['Ticket Subject']\n"
        "df['duration_bucket'] = pd.qcut(df['duration_hours'], q=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])\n\n"
        "prod_freq = df['Product Purchased'].value_counts(normalize=True)\n"
        "df['product_freq'] = df['Product Purchased'].map(prod_freq)\n\n"
        "top10 = df['Product Purchased'].value_counts().head(10).index.tolist()\n"
        "df['product_top10'] = df['Product Purchased'].apply(lambda x: x if x in top10 else 'Other')\n\n"
        "y = df['Customer Satisfaction Rating'].values\n"
        "y_binned = np.round(y).astype(int)\n\n"
        "X_train_idx, X_test_idx = train_test_split(\n"
        "    np.arange(len(df)), test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y_binned\n"
        ")\n"
        "df_train = df.iloc[X_train_idx].copy()\n"
        "df_test = df.iloc[X_test_idx].copy()\n"
        "y_train = y[X_train_idx]\n"
        "y_test = y[X_test_idx]\n\n"
        "print(f'Treino: {len(df_train)} | Teste: {len(df_test)}')\n"
        "print(f'CSAT treino: media={y_train.mean():.3f} | CSAT teste: media={y_test.mean():.3f}')"
    ))

    cells.append(md("## Secao 2: Definicao dos Experimentos"))

    cells.append(code(
        "EXPERIMENTS = [\n"
        "    {'name': 'A1: Channel+Subject', 'block': 'A', 'features': ['Ticket Channel', 'Ticket Subject']},\n"
        "    {'name': 'A2: +Priority', 'block': 'A', 'features': ['Ticket Channel', 'Ticket Subject', 'Ticket Priority']},\n"
        "    {'name': 'A3: +Type', 'block': 'A', 'features': ['Ticket Channel', 'Ticket Subject', 'Ticket Type']},\n"
        "    {'name': 'A4: +Duration', 'block': 'A', 'features': ['Ticket Channel', 'Ticket Subject', 'duration_hours']},\n"
        "    {'name': 'A5: +Age', 'block': 'A', 'features': ['Ticket Channel', 'Ticket Subject', 'age_bucket']},\n"
        "    {'name': 'A6: Full Cat', 'block': 'A', 'features': ['Ticket Channel', 'Ticket Subject', 'Ticket Priority', 'Ticket Type']},\n"
        "    {'name': 'A7: Kitchen Sink', 'block': 'A', 'features': ['Ticket Channel', 'Ticket Subject', 'Ticket Priority', 'Ticket Type', 'duration_hours', 'age_bucket']},\n"
        "    {'name': 'B1: +Pair', 'block': 'B', 'features': ['Ticket Channel', 'Ticket Subject', 'Ticket Priority', 'Ticket Type', 'channel_subject']},\n"
        "    {'name': 'B2: +Duration Int', 'block': 'B', 'features': ['Ticket Channel', 'Ticket Subject', 'Ticket Priority', 'Ticket Type', 'duration_hours', 'age_bucket', 'channel_subject', 'duration_bucket']},\n"
        "    {'name': 'B3: Full Int', 'block': 'B', 'features': ['Ticket Channel', 'Ticket Subject', 'Ticket Priority', 'Ticket Type', 'duration_hours', 'age_bucket', 'channel_subject', 'duration_bucket', 'product_freq']},\n"
        "    {'name': 'C1: +Product Freq', 'block': 'C', 'features': ['Ticket Channel', 'Ticket Subject', 'Ticket Priority', 'Ticket Type', 'product_freq']},\n"
        "    {'name': 'C2: +Product Top10', 'block': 'C', 'features': ['Ticket Channel', 'Ticket Subject', 'Ticket Priority', 'Ticket Type', 'product_top10']},\n"
        "]\n\n"
        "print(f'{\"Experimento\":<25} {\"Bloco\":<6} {\"N Features\":<12}')\n"
        "print('=' * 45)\n"
        "for exp in EXPERIMENTS:\n"
        "    print(f'{exp[\"name\"]:<25} {exp[\"block\"]:<6} {len(exp[\"features\"]):<12}')"
    ))

    cells.append(md("## Secao 3: Execucao dos Experimentos"))

    cells.append(code(
        "NUMERIC_FEATURES = {'duration_hours', 'product_freq'}\n\n"
        "def encode_features(df_tr, df_te, feature_list):\n"
        "    cat_feats = [f for f in feature_list if f not in NUMERIC_FEATURES]\n"
        "    num_feats = [f for f in feature_list if f in NUMERIC_FEATURES]\n"
        "    encoders = {}\n"
        "    X_tr_parts, X_te_parts = [], []\n"
        "    feat_names = []\n"
        "    for f in cat_feats:\n"
        "        enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)\n"
        "        X_tr_parts.append(enc.fit_transform(df_tr[[f]]))\n"
        "        X_te_parts.append(enc.transform(df_te[[f]]))\n"
        "        encoders[f] = enc\n"
        "        feat_names.append(f)\n"
        "    for f in num_feats:\n"
        "        X_tr_parts.append(df_tr[[f]].values)\n"
        "        X_te_parts.append(df_te[[f]].values)\n"
        "        feat_names.append(f)\n"
        "    X_tr = np.hstack(X_tr_parts) if X_tr_parts else np.empty((len(df_tr), 0))\n"
        "    X_te = np.hstack(X_te_parts) if X_te_parts else np.empty((len(df_te), 0))\n"
        "    return X_tr, X_te, feat_names, encoders\n\n"
        "def make_model():\n"
        "    if USE_XGB:\n"
        "        return XGBRegressor(n_estimators=200, max_depth=4, learning_rate=0.1, random_state=RANDOM_STATE, verbosity=0)\n"
        "    else:\n"
        "        return GradientBoostingRegressor(n_estimators=200, max_depth=4, learning_rate=0.1, random_state=RANDOM_STATE)\n\n"
        "def run_experiment(exp, df_tr, df_te, y_tr, y_te):\n"
        "    X_tr, X_te, feat_names, encoders = encode_features(df_tr, df_te, exp['features'])\n"
        "    m = make_model()\n"
        "    m.fit(X_tr, y_tr)\n"
        "    y_pred = m.predict(X_te)\n"
        "    y_pred_round = np.clip(np.round(y_pred), 1, 5)\n"
        "    mae = mean_absolute_error(y_te, y_pred)\n"
        "    rmse = np.sqrt(mean_squared_error(y_te, y_pred))\n"
        "    r2 = r2_score(y_te, y_pred)\n"
        "    accuracy = np.mean(y_pred_round == np.round(y_te))\n"
        "    cv_m = make_model()\n"
        "    cv_scores = cross_val_score(cv_m, X_tr, y_tr, cv=5, scoring='neg_mean_absolute_error')\n"
        "    cv_mae = -cv_scores.mean()\n"
        "    return {'name': exp['name'], 'block': exp['block'], 'n_features': len(feat_names),\n"
        "            'feat_names': feat_names, 'mae_test': mae, 'rmse_test': rmse, 'r2_test': r2,\n"
        "            'accuracy_test': accuracy, 'mae_cv': cv_mae, 'model': m, 'X_test': X_te, 'encoders': encoders}\n\n"
        "print('Executando 12 experimentos...')\n"
        "print('=' * 60)\n"
        "results = []\n"
        "for i, exp in enumerate(EXPERIMENTS):\n"
        "    res = run_experiment(exp, df_train, df_test, y_train, y_test)\n"
        "    results.append(res)\n"
        "    print(f'[{i+1}/12] {res[\"name\"]:<25} MAE={res[\"mae_test\"]:.4f}  RMSE={res[\"rmse_test\"]:.4f}  R2={res[\"r2_test\"]:.4f}  Acc={res[\"accuracy_test\"]:.3f}  CV_MAE={res[\"mae_cv\"]:.4f}')\n"
        "print('=' * 60)\n"
        "print('Todos os experimentos concluidos.')"
    ))

    cells.append(md("## Secao 4: Comparacao dos Experimentos"))

    cells.append(code(
        "results_df = pd.DataFrame([{\n"
        "    'Experimento': r['name'], 'Bloco': r['block'], 'N_Feat': r['n_features'],\n"
        "    'MAE_Teste': r['mae_test'], 'RMSE_Teste': r['rmse_test'],\n"
        "    'R2_Teste': r['r2_test'], 'Accuracy': r['accuracy_test'], 'MAE_CV': r['mae_cv']\n"
        "} for r in results]).sort_values('MAE_Teste')\n\n"
        "print('Ranking por MAE (menor = melhor):')\n"
        "print(results_df.to_string(index=False, float_format='%.4f'))\n\n"
        "baseline_mae = mean_absolute_error(y_test, np.full_like(y_test, y_train.mean()))\n"
        "print(f'Baseline (prever media {y_train.mean():.2f}): MAE = {baseline_mae:.4f}')\n"
        "print(f'Melhor modelo: MAE = {results_df[\"MAE_Teste\"].min():.4f}')\n"
        "print(f'Melhoria sobre baseline: {((baseline_mae - results_df[\"MAE_Teste\"].min()) / baseline_mae * 100):.1f}%')"
    ))

    cells.append(code(
        "colors = {'A': '#3b82f6', 'B': '#f97316', 'C': '#10b981'}\n"
        "fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n\n"
        "sorted_res = sorted(results, key=lambda x: x['mae_test'])\n"
        "names = [r['name'] for r in sorted_res]\n"
        "maes = [r['mae_test'] for r in sorted_res]\n"
        "cols = [colors[r['block']] for r in sorted_res]\n"
        "axes[0].barh(names, maes, color=cols)\n"
        "axes[0].axvline(x=baseline_mae, color='red', linestyle='--', label=f'Baseline: {baseline_mae:.3f}')\n"
        "axes[0].set_xlabel('MAE no Teste')\n"
        "axes[0].set_title('MAE por Experimento (menor = melhor)')\n"
        "axes[0].legend()\n"
        "axes[0].invert_yaxis()\n\n"
        "r2s = [r['r2_test'] for r in sorted_res]\n"
        "axes[1].barh(names, r2s, color=cols)\n"
        "axes[1].axvline(x=0, color='gray', linestyle='-', alpha=0.3)\n"
        "axes[1].set_xlabel('R2 no Teste')\n"
        "axes[1].set_title('R2 por Experimento (maior = melhor)')\n"
        "axes[1].invert_yaxis()\n\n"
        "plt.tight_layout()\n"
        "plt.savefig('../process-log/screenshots/p5_ml_experiment_comparison.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()"
    ))

    cells.append(md("## Secao 5: Feature Importance — Melhor Modelo"))

    cells.append(code(
        "best_idx = min(range(len(results)), key=lambda i: results[i]['mae_test'])\n"
        "best = results[best_idx]\n"
        "print(f'Melhor modelo: {best[\"name\"]}')\n"
        "print(f'MAE={best[\"mae_test\"]:.4f}, R2={best[\"r2_test\"]:.4f}, Accuracy={best[\"accuracy_test\"]:.3f}')\n\n"
        "importances = best['model'].feature_importances_\n"
        "feat_imp = pd.DataFrame({'Feature': best['feat_names'], 'Importancia': importances})\n"
        "feat_imp = feat_imp.sort_values('Importancia', ascending=True)\n\n"
        "fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n"
        "axes[0].barh(feat_imp['Feature'], feat_imp['Importancia'], color='#3b82f6')\n"
        "axes[0].set_title('Importancia por Impureza (Gini)')\n"
        "axes[0].set_xlabel('Importancia')\n\n"
        "perm_imp = permutation_importance(best['model'], best['X_test'], y_test, n_repeats=10, random_state=RANDOM_STATE)\n"
        "perm_df = pd.DataFrame({'Feature': best['feat_names'], 'Importancia': perm_imp.importances_mean, 'Std': perm_imp.importances_std})\n"
        "perm_df = perm_df.sort_values('Importancia', ascending=True)\n"
        "axes[1].barh(perm_df['Feature'], perm_df['Importancia'], xerr=perm_df['Std'], color='#f97316')\n"
        "axes[1].set_title('Importancia por Permutacao')\n"
        "axes[1].set_xlabel('Reducao no MAE')\n\n"
        "plt.tight_layout()\n"
        "plt.savefig('../process-log/screenshots/p5_feature_importance.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()\n\n"
        "print('Top features (impureza):')\n"
        "for _, row in feat_imp.sort_values('Importancia', ascending=False).iterrows():\n"
        "    print(f'  {row[\"Feature\"]}: {row[\"Importancia\"]:.4f}')"
    ))

    cells.append(md("## Secao 6: Analise SHAP — Importancia Global"))

    cells.append(code(
        "if USE_SHAP:\n"
        "    explainer = shap.TreeExplainer(best['model'])\n"
        "    shap_values = explainer.shap_values(best['X_test'])\n\n"
        "    plt.figure(figsize=(12, 8))\n"
        "    shap.summary_plot(shap_values, best['X_test'], feature_names=best['feat_names'], show=False, max_display=15)\n"
        "    plt.title('SHAP Summary — Impacto de Cada Feature no CSAT')\n"
        "    plt.tight_layout()\n"
        "    plt.savefig('../process-log/screenshots/p5_shap_summary.png', dpi=150, bbox_inches='tight')\n"
        "    plt.show()\n\n"
        "    plt.figure(figsize=(12, 6))\n"
        "    shap.summary_plot(shap_values, best['X_test'], feature_names=best['feat_names'], plot_type='bar', show=False, max_display=15)\n"
        "    plt.title('SHAP — Importancia Media Absoluta')\n"
        "    plt.tight_layout()\n"
        "    plt.savefig('../process-log/screenshots/p5_shap_bar.png', dpi=150, bbox_inches='tight')\n"
        "    plt.show()\n\n"
        "    mean_abs_shap = np.abs(shap_values).mean(axis=0)\n"
        "    top3_idx = np.argsort(mean_abs_shap)[-3:][::-1]\n"
        "    fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n"
        "    for i, idx in enumerate(top3_idx):\n"
        "        plt.sca(axes[i])\n"
        "        shap.dependence_plot(idx, shap_values, best['X_test'], feature_names=best['feat_names'], show=False, ax=axes[i])\n"
        "        axes[i].set_title(f'Dependencia: {best[\"feat_names\"][idx]}')\n"
        "    plt.tight_layout()\n"
        "    plt.savefig('../process-log/screenshots/p5_shap_dependence.png', dpi=150, bbox_inches='tight')\n"
        "    plt.show()\n"
        "    print('SHAP global concluido.')\n"
        "else:\n"
        "    shap_values = None\n"
        "    print('SHAP nao disponivel.')"
    ))

    cells.append(md("## Secao 7: SHAP Interacoes"))

    cells.append(code(
        "if USE_SHAP and len(best['feat_names']) <= 10:\n"
        "    try:\n"
        "        print('Calculando SHAP interaction values...')\n"
        "        shap_interaction = explainer.shap_interaction_values(best['X_test'])\n"
        "        mean_inter = np.abs(shap_interaction).mean(axis=0)\n"
        "        np.fill_diagonal(mean_inter, 0)\n"
        "        plt.figure(figsize=(10, 8))\n"
        "        sns.heatmap(mean_inter, xticklabels=best['feat_names'], yticklabels=best['feat_names'],\n"
        "                    cmap='YlOrRd', annot=True, fmt='.4f')\n"
        "        plt.title('SHAP — Matriz de Interacoes')\n"
        "        plt.tight_layout()\n"
        "        plt.savefig('../process-log/screenshots/p5_shap_interactions.png', dpi=150, bbox_inches='tight')\n"
        "        plt.show()\n"
        "        n_feat = len(best['feat_names'])\n"
        "        pairs = []\n"
        "        for i in range(n_feat):\n"
        "            for j in range(i+1, n_feat):\n"
        "                pairs.append((best['feat_names'][i], best['feat_names'][j], mean_inter[i, j]))\n"
        "        pairs.sort(key=lambda x: x[2], reverse=True)\n"
        "        print('Top 5 pares com maior interacao:')\n"
        "        for f1, f2, val in pairs[:5]:\n"
        "            print(f'  {f1} x {f2}: {val:.4f}')\n"
        "    except Exception as e:\n"
        "        print(f'Erro SHAP interactions: {e}')\n"
        "        shap_interaction = None\n"
        "elif USE_SHAP:\n"
        "    print(f'Muitas features ({len(best[\"feat_names\"])}), pulando interaction values.')\n"
        "    shap_interaction = None\n"
        "else:\n"
        "    shap_interaction = None"
    ))

    cells.append(md("## Secao 8: SHAP por Segmento"))

    cells.append(code(
        "if USE_SHAP and shap_values is not None:\n"
        "    shap_df = pd.DataFrame(shap_values, columns=best['feat_names'])\n"
        "    shap_df['channel'] = df_test['Ticket Channel'].values\n"
        "    shap_df['subject'] = df_test['Ticket Subject'].values\n"
        "    shap_df['csat'] = y_test\n\n"
        "    # Por Canal\n"
        "    fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n"
        "    channels = sorted(df_test['Ticket Channel'].unique())\n"
        "    for i, ch in enumerate(channels):\n"
        "        ax = axes[i // 2, i % 2]\n"
        "        ch_shap = shap_df[shap_df['channel'] == ch][best['feat_names']].abs().mean()\n"
        "        ch_shap = ch_shap.sort_values(ascending=True)\n"
        "        ax.barh(ch_shap.index, ch_shap.values, color='#3b82f6')\n"
        "        ax.set_title(f'Importancia SHAP — {ch}')\n"
        "        ax.set_xlabel('Media |SHAP|')\n"
        "    plt.suptitle('SHAP por Canal', fontsize=14, y=1.02)\n"
        "    plt.tight_layout()\n"
        "    plt.savefig('../process-log/screenshots/p5_shap_by_channel.png', dpi=150, bbox_inches='tight')\n"
        "    plt.show()\n\n"
        "    # Por Subject top 5\n"
        "    top5_subj = df_test['Ticket Subject'].value_counts().head(5).index.tolist()\n"
        "    fig, axes = plt.subplots(1, 5, figsize=(25, 6))\n"
        "    for i, subj in enumerate(top5_subj):\n"
        "        subj_shap = shap_df[shap_df['subject'] == subj][best['feat_names']].abs().mean()\n"
        "        subj_shap = subj_shap.sort_values(ascending=True)\n"
        "        axes[i].barh(subj_shap.index, subj_shap.values, color='#f97316')\n"
        "        axes[i].set_title(f'{subj[:20]}', fontsize=10)\n"
        "    plt.suptitle('SHAP por Assunto (top 5)', fontsize=14, y=1.02)\n"
        "    plt.tight_layout()\n"
        "    plt.savefig('../process-log/screenshots/p5_shap_by_subject.png', dpi=150, bbox_inches='tight')\n"
        "    plt.show()\n"
        "    print('Analise por segmento concluida.')\n"
        "else:\n"
        "    print('SHAP nao disponivel.')"
    ))

    cells.append(md("## Secao 9: Validacao Cruzada com Diagnostico Manual"))

    cells.append(code(
        "REDIRECT_VIABLE = {\n"
        "    'Email': {'Phone': True, 'Chat': True, 'Social media': False},\n"
        "    'Chat': {'Phone': True, 'Email': True, 'Social media': False},\n"
        "    'Phone': {'Email': True, 'Chat': True, 'Social media': False},\n"
        "    'Social media': {'Email': True, 'Phone': True, 'Chat': False},\n"
        "}\n\n"
        "channels = sorted(df['Ticket Channel'].unique())\n"
        "subjects = sorted(df['Ticket Subject'].unique())\n\n"
        "subject_channel_csat = {}\n"
        "for sub in subjects:\n"
        "    ch_stats = []\n"
        "    for ch in channels:\n"
        "        pair_data = df[(df['Ticket Channel'] == ch) & (df['Ticket Subject'] == sub)]\n"
        "        if len(pair_data) >= 3:\n"
        "            ch_stats.append({'channel': ch, 'avg_csat': round(pair_data['Customer Satisfaction Rating'].mean(), 2)})\n"
        "    subject_channel_csat[sub] = sorted(ch_stats, key=lambda x: -x['avg_csat'])\n\n"
        "pair_diagnostics = []\n"
        "for ch in channels:\n"
        "    for sub in subjects:\n"
        "        pair_data = df[(df['Ticket Channel'] == ch) & (df['Ticket Subject'] == sub)]\n"
        "        if len(pair_data) < 3:\n"
        "            continue\n"
        "        r_pair, _ = pearsonr(pair_data['duration_hours'], pair_data['Customer Satisfaction Rating'])\n"
        "        r_pair = round(r_pair, 3)\n"
        "        pair_csat = round(pair_data['Customer Satisfaction Rating'].mean(), 2)\n"
        "        ch_stats = subject_channel_csat.get(sub, [])\n"
        "        best_ch = ch_stats[0] if ch_stats else None\n"
        "        if r_pair < -0.3:\n"
        "            scenario = 'acelerar'\n"
        "        elif r_pair > 0.3:\n"
        "            scenario = 'desacelerar'\n"
        "        else:\n"
        "            csat_gap = best_ch['avg_csat'] - pair_csat if best_ch else 0\n"
        "            if csat_gap > 0.5 and best_ch and best_ch['channel'] != ch:\n"
        "                viable = [c for c in ch_stats if c['channel'] != ch and c['avg_csat'] > pair_csat + 0.3\n"
        "                         and REDIRECT_VIABLE.get(ch, {}).get(c['channel'], False)]\n"
        "                scenario = 'redirecionar' if viable else 'quarentena'\n"
        "            elif pair_csat >= 3.5:\n"
        "                scenario = 'manter'\n"
        "            else:\n"
        "                all_bad = all(c['avg_csat'] < 3.0 for c in ch_stats)\n"
        "                scenario = 'quarentena' if (all_bad and pair_csat < 3.0) else 'liberar'\n"
        "        pair_diagnostics.append({'channel': ch, 'subject': sub, 'scenario': scenario, 'r_pair': r_pair, 'pair_csat': pair_csat})\n\n"
        "diag_df = pd.DataFrame(pair_diagnostics)\n"
        "print(f'Diagnostico replicado: {len(diag_df)} pares')\n"
        "print(diag_df['scenario'].value_counts().to_string())"
    ))

    cells.append(code(
        "if USE_SHAP and shap_values is not None and 'duration_hours' in best['feat_names']:\n"
        "    dur_idx = best['feat_names'].index('duration_hours')\n"
        "    shap_dur = shap_values[:, dur_idx]\n"
        "    test_pairs = df_test[['Ticket Channel', 'Ticket Subject']].copy()\n"
        "    test_pairs['shap_duration'] = shap_dur\n"
        "    pair_shap = test_pairs.groupby(['Ticket Channel', 'Ticket Subject'])['shap_duration'].mean().reset_index()\n"
        "    pair_shap.columns = ['channel', 'subject', 'mean_shap_duration']\n"
        "    compare = diag_df.merge(pair_shap, on=['channel', 'subject'], how='left').dropna(subset=['mean_shap_duration'])\n\n"
        "    def check_agreement(row):\n"
        "        if row['scenario'] == 'acelerar': return row['mean_shap_duration'] < 0\n"
        "        elif row['scenario'] == 'desacelerar': return row['mean_shap_duration'] > 0\n"
        "        else: return abs(row['mean_shap_duration']) < 0.1\n\n"
        "    compare['agrees'] = compare.apply(check_agreement, axis=1)\n"
        "    agreement_rate = compare['agrees'].mean() * 100\n"
        "    print(f'Taxa de concordancia SHAP vs Diagnostico: {agreement_rate:.1f}%')\n"
        "    for scenario in ['acelerar', 'desacelerar', 'redirecionar', 'quarentena', 'manter', 'liberar']:\n"
        "        s_data = compare[compare['scenario'] == scenario]\n"
        "        if len(s_data) > 0:\n"
        "            rate = s_data['agrees'].mean() * 100\n"
        "            print(f'  {scenario}: {rate:.0f}% ({len(s_data)} pares)')\n\n"
        "    scenario_colors = {'acelerar': '#ef4444', 'desacelerar': '#3b82f6', 'redirecionar': '#f97316',\n"
        "                       'quarentena': '#eab308', 'manter': '#22c55e', 'liberar': '#9ca3af'}\n"
        "    plt.figure(figsize=(12, 8))\n"
        "    for scenario, color in scenario_colors.items():\n"
        "        s_data = compare[compare['scenario'] == scenario]\n"
        "        plt.scatter(s_data['r_pair'], s_data['mean_shap_duration'], c=color, label=scenario, s=80, alpha=0.7, edgecolors='black', linewidths=0.5)\n"
        "    plt.axhline(y=0, color='gray', linestyle='--', alpha=0.5)\n"
        "    plt.axvline(x=-0.3, color='red', linestyle=':', alpha=0.5)\n"
        "    plt.axvline(x=0.3, color='blue', linestyle=':', alpha=0.5)\n"
        "    plt.xlabel('Pearson r (duracao x CSAT) — Diagnostico Manual')\n"
        "    plt.ylabel('Media SHAP(Duration) — Modelo ML')\n"
        "    plt.title('Validacao: Pearson r vs SHAP(Duration) por Par')\n"
        "    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')\n"
        "    plt.tight_layout()\n"
        "    plt.savefig('../process-log/screenshots/p5_shap_vs_pearson.png', dpi=150, bbox_inches='tight')\n"
        "    plt.show()\n"
        "else:\n"
        "    print('Duration nao esta no melhor modelo ou SHAP indisponivel.')"
    ))

    cells.append(md("## Secao 10: Validacao do Modelo"))

    cells.append(code(
        "baseline_mae = mean_absolute_error(y_test, np.full_like(y_test, y_train.mean()))\n"
        "best_mae = results[best_idx]['mae_test']\n"
        "print(f'Baseline (prever media): MAE = {baseline_mae:.4f}')\n"
        "print(f'Melhor modelo ({best[\"name\"]}): MAE = {best_mae:.4f}')\n"
        "print(f'Melhoria: {((baseline_mae - best_mae) / baseline_mae * 100):.1f}%')\n\n"
        "print('Teste de permutacao (10 iteracoes)...')\n"
        "perm_maes = []\n"
        "X_tr_best, X_te_best, _, _ = encode_features(df_train, df_test, EXPERIMENTS[best_idx]['features'])\n"
        "for i in range(10):\n"
        "    y_perm = np.random.RandomState(i).permutation(y_train)\n"
        "    m = make_model()\n"
        "    m.fit(X_tr_best, y_perm)\n"
        "    perm_maes.append(mean_absolute_error(y_test, m.predict(X_te_best)))\n\n"
        "perm_mean = np.mean(perm_maes)\n"
        "perm_std = np.std(perm_maes)\n"
        "z_score = (perm_mean - best_mae) / perm_std if perm_std > 0 else 0\n"
        "print(f'MAE permutado: {perm_mean:.4f} +/- {perm_std:.4f}')\n"
        "print(f'Z-score: {z_score:.2f}')\n"
        "if best_mae < perm_mean - 2 * perm_std:\n"
        "    print('Modelo aprendeu sinal SIGNIFICATIVO (p < 0.05)')\n"
        "elif best_mae < perm_mean:\n"
        "    print('Modelo tem leve vantagem, nao significativa')\n"
        "else:\n"
        "    print('Modelo NAO e melhor que aleatorio')\n\n"
        "plt.figure(figsize=(10, 5))\n"
        "plt.hist(perm_maes, bins=10, alpha=0.7, color='#9ca3af', label='MAE permutado')\n"
        "plt.axvline(x=best_mae, color='#ef4444', linewidth=2, label=f'Modelo real: {best_mae:.4f}')\n"
        "plt.axvline(x=baseline_mae, color='#f97316', linewidth=2, linestyle='--', label=f'Baseline: {baseline_mae:.4f}')\n"
        "plt.xlabel('MAE')\n"
        "plt.ylabel('Frequencia')\n"
        "plt.title('Teste de Permutacao: Modelo Real vs Aleatorio')\n"
        "plt.legend()\n"
        "plt.tight_layout()\n"
        "plt.savefig('../process-log/screenshots/p5_permutation_test.png', dpi=150, bbox_inches='tight')\n"
        "plt.show()"
    ))

    cells.append(md("## Secao 11: Conclusoes"))

    cells.append(code(
        "print('=' * 60)\n"
        "print('CONCLUSOES — EXPERIMENTOS ML')\n"
        "print('=' * 60)\n"
        "print(f'1. MELHOR MODELO: {best[\"name\"]}')\n"
        "print(f'   MAE={best[\"mae_test\"]:.4f}, R2={best[\"r2_test\"]:.4f}, Accuracy={best[\"accuracy_test\"]:.3f}')\n"
        "print('2. TOP FEATURES (impureza):')\n"
        "feat_rank = sorted(zip(best['feat_names'], best['model'].feature_importances_), key=lambda x: -x[1])\n"
        "for fname, imp in feat_rank[:5]:\n"
        "    print(f'   {fname}: {imp:.4f}')\n"
        "if USE_SHAP and shap_values is not None:\n"
        "    print('3. TOP FEATURES (SHAP):')\n"
        "    mean_shap = np.abs(shap_values).mean(axis=0)\n"
        "    shap_rank = sorted(zip(best['feat_names'], mean_shap), key=lambda x: -x[1])\n"
        "    for fname, val in shap_rank[:5]:\n"
        "        print(f'   {fname}: {val:.4f}')\n"
        "print(f'4. BASELINE MAE: {baseline_mae:.4f}')\n"
        "print(f'   Melhor MAE: {best_mae:.4f}')\n"
        "print(f'   Melhoria: {((baseline_mae - best_mae) / baseline_mae * 100):.1f}%')\n"
        "print('5. VARIAVEIS ACIONAVEIS:')\n"
        "print('   - Canal: variavel de roteamento primaria')\n"
        "print('   - Assunto: define tipo de demanda')\n"
        "print('   - Duracao: indica se velocidade importa para CSAT neste par')\n"
        "print('=' * 60)"
    ))

    build_notebook(cells, '05_ml_experiments.ipynb')


# =====================================================
# BUILD ALL
# =====================================================
os.chdir('/Users/koristuvac/DEV/optiflow/analysis')
build_05()
