import { loadData } from "@/lib/data";
import { DataFreshness, GovernanceChecklist, LimitationCallout, SectionHeader } from "@/components/ui";
import { SimpleBarChart } from "@/components/DashboardCharts";

interface Governance { cutoff: string; checks: Array<{ label: string; passed: boolean }>; decision_groups: Array<{ category: string; range: string; count: number }>; decision_count: number }
const checkLabels = ["Sem PII", "Sem vazamento futuro", "Sem alegações causais", "Sem pontuação preditiva", "Sem intervenção automática", "Regras determinísticas", "Revisão humana", "Saídas reconciliadas", "Regras versionadas", "Fluxo reproduzível", "Sensibilidade principal e estrita", "Limitações explícitas"];
const groupLabels = ["Dados", "Temporal", "Sobrevivência", "Jornadas", "Grafo", "Fila de revisão", "Experimentação"];

export default async function GovernancePage() {
  const governance = await loadData<Governance>("governance.json");
  const checks = governance.checks.map((check, index) => ({ ...check, label: checkLabels[index] }));
  const groups = governance.decision_groups.map((group, index) => ({ ...group, category: groupLabels[index] }));
  return <div><SectionHeader eyebrow="Governança" title="As proteções fazem parte do produto." description="Privacidade, integridade temporal, reprodutibilidade e pontos de decisão humana permanecem visíveis em vez de escondidos em anexos técnicos." /><DataFreshness cutoff={governance.cutoff} /><div className="mt-7"><GovernanceChecklist checks={checks} /></div><section className="mt-7 grid gap-5 xl:grid-cols-[1fr_.9fr]"><SimpleBarChart data={groups} category="category" value="count" title="Decisões registradas por domínio" subtitle={`${governance.decision_count} decisões versionadas até o Laboratório de Experimentos`} summary="As decisões cobrem dados, lógica temporal, sobrevivência, jornadas, grafo, filas e experimentação." /><div className="grid gap-4 sm:grid-cols-2"><ListPanel title="Premissas" items={["Somente dados observacionais históricos.", "Registros diários de data e hora podem limitar a ordenação dentro do mesmo dia.", "MRR associado é contexto, não perda ou exposição."]} /><ListPanel title="Alertas" items={["Alertas de origem permanecem visíveis.", "A evidência de reativação é limitada.", "A maioria dos desenhos experimentais ainda não é viável."]} /><ListPanel title="Operações proibidas" items={["Contato com clientes", "Alteração automática de plano", "Cancelamento automático", "Execução de experimento ao vivo", "Transferência externa de dados por conta"]} /><ListPanel title="Decisões humanas" items={["Resolver revisão de qualidade", "Inspecionar evidência de jornada", "Aprovar desenho experimental", "Autorizar qualquer fluxo operacional futuro"]} /></div></section><div className="mt-7"><LimitationCallout>O modo de demonstração é um snapshot local fixo, sem autenticação, observabilidade de produção, integrações de saída, bancos externos ou modelo de linguagem.</LimitationCallout></div></div>;
}
function ListPanel({ title, items }: { title: string; items: string[] }) { return <article className="panel p-5"><h3 className="font-semibold">{title}</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-slate-700">{items.map((item) => <li key={item}>{item}</li>)}</ul></article>; }
