import { loadData } from "@/lib/data";
import type { WatchlistItem } from "@/lib/types";
import { DataFreshness, LimitationCallout, SectionHeader } from "@/components/ui";
import { MultiColorBarChart, SimpleBarChart } from "@/components/DashboardCharts";
import { formatIntegerPtBr } from "@/lib/format";
import { WatchlistTable } from "@/components/WatchlistExplorer";

interface Summary { cutoff: string; unique_accounts: number; items: number; queues: Array<{ queue: string; category: string; items: number; unique_accounts: number; associated_mrr: number }>; priority_by_unique_accounts: Array<{ priority: string; accounts: number }>; data_quality_backlog_accounts: number }
interface Items { items: WatchlistItem[] }

export default async function WatchlistPage() {
  const [summary, items] = await Promise.all([loadData<Summary>("watchlist_summary.json"), loadData<Items>("watchlist_items_demo.json")]);
  return <div><SectionHeader eyebrow="Fila de revisão" title="Priorização governada para investigação humana." description="As filas de revisão comportamental e de qualidade permanecem separadas. Evidências determinísticas explicam por que um perfil anônimo aparece sem prescrever uma ação." /><DataFreshness cutoff={summary.cutoff} /><div className="mt-7 grid gap-4 sm:grid-cols-3"><article className="panel p-5"><p className="data-label">Contas únicas</p><p className="mt-2 font-mono text-3xl font-semibold">{formatIntegerPtBr(summary.unique_accounts)}</p><p className="mt-2 text-sm text-muted">Em filas delimitadas de revisão humana</p></article><article className="panel p-5"><p className="data-label">Itens da fila</p><p className="mt-2 font-mono text-3xl font-semibold">{formatIntegerPtBr(summary.items)}</p><p className="mt-2 text-sm text-muted">Regras podem criar mais de um item por conta</p></article><article className="panel p-5"><p className="data-label">Pendências de qualidade</p><p className="mt-2 font-mono text-3xl font-semibold">{formatIntegerPtBr(summary.data_quality_backlog_accounts)}</p><p className="mt-2 text-sm text-muted">Não representam ranking comportamental</p></article></div><section className="mt-6 grid gap-5 xl:grid-cols-2"><SimpleBarChart data={summary.queues} category="queue" value="unique_accounts" title="Filas de revisão" subtitle="Contas anônimas únicas por fila" summary="A revisão de qualidade aparece separada de seis filas de investigação comportamental." /><MultiColorBarChart data={summary.priority_by_unique_accounts} category="priority" value="accounts" title="Maior prioridade por conta única" subtitle="Matriz determinística P1–P4 · sem probabilidade" summary="As prioridades organizam a revisão humana e não representam probabilidades individuais de risco." /></section><div className="mt-6"><LimitationCallout>MRR associado não representa receita em risco. Valores agregados oferecem apenas contexto de materialidade.</LimitationCallout></div><div className="mt-7"><WatchlistTable items={items.items} /></div></div>;
}
