import { loadData } from "@/lib/data";
import type { WatchlistItem } from "@/lib/types";
import { DataFreshness, LimitationCallout, SectionHeader } from "@/components/ui";
import { MultiColorBarChart, SimpleBarChart } from "@/components/DashboardCharts";
import { WatchlistTable } from "@/components/WatchlistExplorer";

interface Summary { cutoff: string; unique_accounts: number; items: number; queues: Array<{ queue: string; category: string; items: number; unique_accounts: number; associated_mrr: number }>; priority_by_unique_accounts: Array<{ priority: string; accounts: number }>; data_quality_backlog_accounts: number; associated_mrr_note: string }
interface Items { items: WatchlistItem[] }

export default async function WatchlistPage() {
  const [summary, items] = await Promise.all([loadData<Summary>("watchlist_summary.json"), loadData<Items>("watchlist_items_demo.json")]);
  return <div><SectionHeader eyebrow="Intervention watchlist" title="Governed prioritization for human investigation." description="Behavioral review queues and data-quality work remain separate. Deterministic evidence explains why an anonymous account appears without prescribing an action." /><DataFreshness cutoff={summary.cutoff} /><div className="mt-7 grid gap-4 sm:grid-cols-3"><article className="panel p-5"><p className="data-label">Unique accounts</p><p className="mt-2 font-mono text-3xl font-semibold">{summary.unique_accounts}</p><p className="mt-2 text-sm text-muted">Across bounded human-review queues</p></article><article className="panel p-5"><p className="data-label">Watchlist items</p><p className="mt-2 font-mono text-3xl font-semibold">{summary.items}</p><p className="mt-2 text-sm text-muted">Rules can create multiple items per account</p></article><article className="panel p-5"><p className="data-label">Data quality backlog</p><p className="mt-2 font-mono text-3xl font-semibold">{summary.data_quality_backlog_accounts}</p><p className="mt-2 text-sm text-muted">Not a behavioral ranking</p></article></div><section className="mt-6 grid gap-5 xl:grid-cols-2"><SimpleBarChart data={summary.queues} category="queue" value="unique_accounts" title="Watchlist queues" subtitle="Unique anonymous accounts by review queue" summary="Data-quality review is shown separately from six behavioral investigation queues." /><MultiColorBarChart data={summary.priority_by_unique_accounts} category="priority" value="accounts" title="Highest priority by unique account" subtitle="Deterministic P1–P4 matrix · no probability" summary="Priorities organize human review and do not represent individual risk probabilities." /></section><div className="mt-6"><LimitationCallout>{summary.associated_mrr_note} Aggregated values provide material context only.</LimitationCallout></div><div className="mt-7"><WatchlistTable items={items.items} /></div></div>;
}
