"""
Fase 4 — Coleta de Dados Reais via Apify (5 plataformas)
==========================================================
Coleta posts de perfis reais via Apify para todas as plataformas do dataset.
Normaliza para o mesmo schema para cruzamento com o dataset.

Plataformas suportadas:
- Instagram: apify/instagram-scraper
- TikTok: clockworks/tiktok-scraper
- YouTube: streamers/youtube-scraper
- RedNote: easyapi/all-in-one-rednote-xiaohongshu-scraper
- Bilibili: kuaima/bilibili-detail

Uso: python 04_apify_collector.py --profile @perfil --platform instagram
"""

import json
import os
import sys
import argparse
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(BASE_DIR, "analysis", "outputs")
os.makedirs(OUTPUT_DIR, exist_ok=True)

APIFY_TOKEN = os.environ.get("APIFY_TOKEN", "")

ACTORS = {
    "instagram": "apify/instagram-scraper",
    "tiktok": "clockworks/tiktok-scraper",
    "youtube": "streamers/youtube-scraper",
    "rednote": "easyapi/all-in-one-rednote-xiaohongshu-scraper",
    "bilibili": "kuaima/bilibili-detail",
}


def get_apify_client():
    try:
        from apify_client import ApifyClient
    except ImportError:
        print("ERRO: apify-client nao instalado. Rode: pip install apify-client")
        sys.exit(1)

    if not APIFY_TOKEN:
        print("ERRO: APIFY_TOKEN nao configurado. Exporte a variavel ou adicione ao .env")
        sys.exit(1)

    return ApifyClient(APIFY_TOKEN)


# ============================================================
# COLETORES POR PLATAFORMA
# ============================================================

def collect_instagram(profile, max_posts=30):
    client = get_apify_client()
    username = profile.lstrip("@")
    print(f"Coletando posts de @{username} no Instagram...")

    run_input = {
        "addParentData": False,
        "directUrls": [f"https://www.instagram.com/{username}/"],
        "resultsLimit": max_posts,
        "resultsType": "posts",
        "searchLimit": 1,
        "searchType": "hashtag",
    }

    run = client.actor(ACTORS["instagram"]).call(run_input=run_input)
    items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
    print(f"Coletados {len(items)} posts")
    return items


def collect_tiktok(profile, max_posts=30):
    client = get_apify_client()
    username = profile.lstrip("@")
    print(f"Coletando posts de @{username} no TikTok...")

    run_input = {
        "commentsPerPost": 0,
        "excludePinnedPosts": False,
        "hashtags": [],
        "maxFollowersPerProfile": 0,
        "maxFollowingPerProfile": 0,
        "maxRepliesPerComment": 0,
        "proxyCountryCode": "None",
        "resultsPerPage": max_posts,
        "scrapeRelatedVideos": False,
        "shouldDownloadAvatars": False,
        "shouldDownloadCovers": False,
        "shouldDownloadMusicCovers": False,
        "shouldDownloadSlideshowImages": False,
        "shouldDownloadVideos": False,
        # Profile URL para coleta
        "profiles": [f"https://www.tiktok.com/@{username}"],
    }

    run = client.actor(ACTORS["tiktok"]).call(run_input=run_input)
    items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
    print(f"Coletados {len(items)} posts")
    return items


def collect_youtube(profile, max_posts=10):
    client = get_apify_client()
    username = profile.lstrip("@")
    print(f"Coletando videos de @{username} no YouTube...")

    run_input = {
        "downloadSubtitles": False,
        "hasCC": False,
        "hasLocation": False,
        "hasSubtitles": False,
        "is360": False,
        "is3D": False,
        "is4K": False,
        "isBought": False,
        "isHD": False,
        "isHDR": False,
        "isLive": False,
        "isVR180": False,
        "maxResultStreams": 0,
        "maxResults": max_posts,
        "maxResultsShorts": 0,
        "preferAutoGeneratedSubtitles": False,
        "saveSubsToKVS": False,
        "searchQueries": [username],
    }

    run = client.actor(ACTORS["youtube"]).call(run_input=run_input)
    items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
    print(f"Coletados {len(items)} videos")
    return items


def collect_rednote(profile, max_posts=30):
    client = get_apify_client()
    profile_url = profile if profile.startswith("http") else f"https://www.xiaohongshu.com/user/profile/{profile.lstrip('@')}"
    print(f"Coletando posts de {profile_url} no RedNote...")

    run_input = {
        "mode": "userPosts",
        "postUrls": [""],
        "profileUrls": [profile_url],
        "maxItems": max_posts,
    }

    run = client.actor(ACTORS["rednote"]).call(run_input=run_input)
    items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
    print(f"Coletados {len(items)} posts")
    return items


def collect_bilibili(profile, max_posts=10):
    """Bilibili requer URLs de videos especificos."""
    client = get_apify_client()
    print(f"Coletando videos do Bilibili...")

    # Bilibili actor recebe URLs de videos, nao perfis
    urls = profile if isinstance(profile, list) else [profile]
    run_input = {
        "startUrls": [{"url": u} for u in urls if u.startswith("http")],
    }

    if not run_input["startUrls"]:
        print("Bilibili requer URLs de videos (ex: https://www.bilibili.com/video/BV1xxx)")
        return []

    run = client.actor(ACTORS["bilibili"]).call(run_input=run_input)
    items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
    print(f"Coletados {len(items)} videos")
    return items


# ============================================================
# NORMALIZADORES
# ============================================================

def normalize_instagram(raw_posts, profile):
    normalized = []
    for i, post in enumerate(raw_posts):
        likes = post.get("likesCount", 0) or 0
        comments = post.get("commentsCount", 0) or 0
        views = post.get("videoViewCount", 0) or post.get("videoPlayCount", 0) or 0
        shares = 0

        if views == 0:
            views = max(likes * 10, 1)

        engagement_rate = ((likes + shares + comments) / views) * 100 if views > 0 else 0

        normalized.append({
            "id": i + 1,
            "platform": "Instagram",
            "content_id": post.get("id", f"ig_{i}"),
            "creator_name": profile.lstrip("@"),
            "content_url": post.get("url", ""),
            "content_type": post.get("type", "image"),
            "post_date": post.get("timestamp", ""),
            "content_description": (post.get("caption", "") or "")[:200],
            "hashtags": ",".join(post.get("hashtags", []) or []),
            "views": views,
            "likes": likes,
            "shares": shares,
            "comments_count": comments,
            "follower_count": post.get("ownerFollowerCount", 0) or 0,
            "is_sponsored": post.get("isPaid", False),
            "engagement_rate": round(engagement_rate, 4),
        })
    return normalized


def normalize_tiktok(raw_posts, profile):
    normalized = []
    for i, post in enumerate(raw_posts):
        likes = post.get("diggCount", 0) or post.get("likes", 0) or 0
        comments = post.get("commentCount", 0) or post.get("comments", 0) or 0
        shares = post.get("shareCount", 0) or post.get("shares", 0) or 0
        views = post.get("playCount", 0) or post.get("plays", 0) or 1

        engagement_rate = ((likes + shares + comments) / views) * 100 if views > 0 else 0

        # Extrair hashtags
        hashtags = []
        for h in (post.get("hashtags", []) or []):
            if isinstance(h, dict):
                hashtags.append(h.get("name", ""))
            elif isinstance(h, str):
                hashtags.append(h)

        normalized.append({
            "id": i + 1,
            "platform": "TikTok",
            "content_id": post.get("id", f"tt_{i}"),
            "creator_name": profile.lstrip("@"),
            "content_url": post.get("webVideoUrl", ""),
            "content_type": "video",
            "post_date": post.get("createTimeISO", ""),
            "content_description": (post.get("text", "") or post.get("desc", "") or "")[:200],
            "hashtags": ",".join(hashtags),
            "views": views,
            "likes": likes,
            "shares": shares,
            "comments_count": comments,
            "follower_count": post.get("authorMeta", {}).get("fans", 0) if isinstance(post.get("authorMeta"), dict) else 0,
            "is_sponsored": False,
            "engagement_rate": round(engagement_rate, 4),
        })
    return normalized


def normalize_youtube(raw_posts, profile):
    normalized = []
    for i, post in enumerate(raw_posts):
        # YouTube scraper retorna formato diferente
        views = post.get("viewCount", 0) or post.get("view_count", 0) or 0
        likes = post.get("likeCount", 0) or post.get("like_count", 0) or 0
        comments = post.get("commentCount", 0) or post.get("reply_count", 0) or 0
        shares = 0

        # Tentar parsear contagens em texto (ex: "76.7万")
        if isinstance(views, str):
            views = _parse_count(views)
        if isinstance(likes, str):
            likes = _parse_count(likes)
        if isinstance(comments, str):
            comments = _parse_count(comments)

        views = max(views, 1)
        engagement_rate = ((likes + shares + comments) / views) * 100 if views > 0 else 0

        normalized.append({
            "id": i + 1,
            "platform": "YouTube",
            "content_id": post.get("id", f"yt_{i}"),
            "creator_name": post.get("author", profile.lstrip("@")),
            "content_url": post.get("url", ""),
            "content_type": "video",
            "post_date": post.get("pubdate", post.get("date", "")),
            "content_description": (post.get("title", "") or post.get("description", "") or "")[:200],
            "hashtags": ",".join(post.get("tags", []) or []),
            "views": views,
            "likes": likes,
            "shares": shares,
            "comments_count": comments,
            "follower_count": 0,
            "is_sponsored": False,
            "engagement_rate": round(engagement_rate, 4),
        })
    return normalized


def normalize_rednote(raw_posts, profile):
    normalized = []
    for i, post in enumerate(raw_posts):
        post_data = post.get("postData", post.get("item", {}))
        note_card = post_data.get("note_card", post_data)

        user = note_card.get("user", {})
        interact = note_card.get("interact_info", note_card.get("interactInfo", {}))

        likes_raw = interact.get("liked_count", interact.get("likedCount", 0))
        likes = _parse_count(likes_raw) if isinstance(likes_raw, str) else (likes_raw or 0)
        views = max(likes * 10, 1)  # RedNote nao mostra views publicamente
        comments = 0
        shares = 0

        engagement_rate = ((likes + shares + comments) / views) * 100 if views > 0 else 0

        title = note_card.get("display_title", post_data.get("displayTitle", ""))
        creator = user.get("nick_name", user.get("nickName", user.get("nickname", profile.lstrip("@"))))

        normalized.append({
            "id": i + 1,
            "platform": "RedNote",
            "content_id": post_data.get("id", note_card.get("noteId", f"rn_{i}")),
            "creator_name": creator,
            "content_url": post.get("link", post_data.get("postUrl", "")),
            "content_type": note_card.get("type", "normal"),
            "post_date": post.get("scrapedAt", ""),
            "content_description": title[:200],
            "hashtags": "",
            "views": views,
            "likes": likes,
            "shares": shares,
            "comments_count": comments,
            "follower_count": 0,
            "is_sponsored": False,
            "engagement_rate": round(engagement_rate, 4),
        })
    return normalized


def normalize_bilibili(raw_posts, profile):
    normalized = []
    for i, post in enumerate(raw_posts):
        views = _parse_count(post.get("view_count", 0))
        likes = _parse_count(post.get("like_count", 0))
        comments = _parse_count(post.get("reply_count", 0))
        shares = _parse_count(post.get("share_count", 0))
        coins = _parse_count(post.get("coin_count", 0))

        views = max(views, 1)
        engagement_rate = ((likes + shares + comments + coins) / views) * 100 if views > 0 else 0

        normalized.append({
            "id": i + 1,
            "platform": "Bilibili",
            "content_id": post.get("id", f"bili_{i}"),
            "creator_name": post.get("author", profile.lstrip("@")),
            "content_url": post.get("url", ""),
            "content_type": "video",
            "post_date": post.get("pubdate", ""),
            "content_description": (post.get("title", "") or post.get("description", "") or "")[:200],
            "hashtags": ",".join(post.get("tags", []) or []),
            "views": views,
            "likes": likes,
            "shares": shares,
            "comments_count": comments,
            "follower_count": 0,
            "is_sponsored": False,
            "engagement_rate": round(engagement_rate, 4),
        })
    return normalized


def _parse_count(value):
    """Parseia contagens em texto como '76.7万' ou '5.9万' para int."""
    if isinstance(value, (int, float)):
        return int(value)
    if not isinstance(value, str):
        return 0
    value = value.strip()
    if not value:
        return 0
    try:
        # Formato chinês: 万 = 10000
        if "万" in value:
            return int(float(value.replace("万", "")) * 10000)
        if "亿" in value:
            return int(float(value.replace("亿", "")) * 100000000)
        # Formato abreviado: K, M
        if value.upper().endswith("K"):
            return int(float(value[:-1]) * 1000)
        if value.upper().endswith("M"):
            return int(float(value[:-1]) * 1000000)
        return int(float(value.replace(",", "")))
    except (ValueError, TypeError):
        return 0


# ============================================================
# ANALISE E SAIDA
# ============================================================

def analyze_collected(posts):
    if not posts:
        return {"error": "Nenhum post coletado"}

    import numpy as np
    engagements = [p["engagement_rate"] for p in posts]
    sorted_posts = sorted(posts, key=lambda x: x["engagement_rate"], reverse=True)

    return {
        "total_posts": len(posts),
        "avg_engagement": round(float(np.mean(engagements)), 2),
        "median_engagement": round(float(np.median(engagements)), 2),
        "std_engagement": round(float(np.std(engagements)), 2),
        "avg_views": round(float(np.mean([p["views"] for p in posts])), 0),
        "avg_likes": round(float(np.mean([p["likes"] for p in posts])), 0),
        "top_3_posts": [
            {"description": p["content_description"][:80], "engagement": p["engagement_rate"], "url": p["content_url"]}
            for p in sorted_posts[:3]
        ],
        "worst_3_posts": [
            {"description": p["content_description"][:80], "engagement": p["engagement_rate"], "url": p["content_url"]}
            for p in sorted_posts[-3:]
        ],
    }


COLLECTORS = {
    "instagram": (collect_instagram, normalize_instagram),
    "tiktok": (collect_tiktok, normalize_tiktok),
    "youtube": (collect_youtube, normalize_youtube),
    "rednote": (collect_rednote, normalize_rednote),
    "bilibili": (collect_bilibili, normalize_bilibili),
}


def main():
    parser = argparse.ArgumentParser(description="Coleta dados de perfil via Apify")
    parser.add_argument("--profile", required=True, help="Username ou URL do perfil")
    parser.add_argument("--platform", required=True, choices=list(ACTORS.keys()))
    parser.add_argument("--max-posts", type=int, default=30)
    args = parser.parse_args()

    collector, normalizer = COLLECTORS[args.platform]

    raw = collector(args.profile, args.max_posts)
    if not raw:
        print("Nenhum post coletado. Verifique o token e o perfil.")
        sys.exit(1)

    posts = normalizer(raw, args.profile)
    analysis = analyze_collected(posts)

    output = {
        "_meta": {
            "generated_at": datetime.now().isoformat(),
            "data_source": "apify_live",
            "profile": args.profile,
            "platform": args.platform,
            "actor": ACTORS[args.platform],
            "posts_collected": len(posts),
        },
        "analysis": analysis,
        "posts": posts,
    }

    filename = f"apify_{args.platform}_{args.profile.lstrip('@').replace('/', '_')}.json"
    path = os.path.join(OUTPUT_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False, default=str)

    print(f"\nSalvo em: {path}")
    print(f"Posts: {analysis['total_posts']}")
    print(f"Engagement medio: {analysis['avg_engagement']}%")
    if analysis['top_3_posts']:
        print(f"Top post: {analysis['top_3_posts'][0]['engagement']}%")


if __name__ == "__main__":
    main()
